### ISSUE TITLE
Support JSON as Flows

### ISSUE THREAD

**Issue by raphael-goetz** [code0-tech/aquila#25]
Aquila should be able to be started with a JSON (containing flows) specified by a path (as env. variable). Only if ENABLE_SCHEDULED_UPDATE and ENABLE_GRPC_UPDATE is false and the path is present.

**Comment by julian-siebert** [comment]
@nicosammito @Taucher2003

**Comment by nicosammito** [comment]
> @nicosammito @Taucher2003
Fwd -> @raphael-goetz @Taucher2003

**Comment by Taucher2003** [comment]
@julian-siebert instead of loading the flows vie GRPC from Sagittarius, they are loaded from a JSON file. This can be used for cases, where no internet connection is available.
